### ISSUE TITLE
 SGPI-2017-04-30_LIWIXI.ZIP not found on server

### ISSUE THREAD

**Issue by Skellyrox** [jbrzusto/sensorgnome#62]
I need to create a new SD card for a Raspberry Pi system, but the zip file that is needed is not on the server. This is the message I receive when I click on the link:

Not Found
The requested URL /Raspberry_Pi_Sensorgnome/SGPI-2017-04-30_LIWIXI.ZIP was not found on this server.
Apache/2.2.22 (Debian) Server at public.sensorgnome.org Port 443

**Comment by jbrzusto** [comment]
From where did you follow that link (I'd like to fix it)?

The SG-Pi images are here:
https://public.sensorgnome.org/Raspberry_Pi_Sensorgnome/
